# Generated by Django 4.1 on 2022-08-25 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_mode',
            field=models.IntegerField(blank=True, default=12, null=True, verbose_name='Число режимов'),
        ),
        migrations.AlterField(
            model_name='product',
            name='power',
            field=models.IntegerField(blank=True, default=500, null=True, verbose_name='Мощьность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text_title',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название оборудования')),
                ('text_title', models.CharField(blank=True, max_length=350, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Картинка')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product')),
            ],
            options={
                'verbose_name': 'Интро',
                'verbose_name_plural': 'Интро',
            },
        ),
    ]
