# Generated by Django 4.1 on 2022-08-25 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название прибора'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product'),
        ),
    ]
