# Generated by Django 4.1 on 2022-08-25 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_intro_name_alter_intro_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='intro', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product'),
        ),
    ]
