# Generated by Django 4.1 on 2022-08-25 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_intro_image_alter_intro_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product'),
        ),
    ]
