# Generated by Django 4.1 on 2022-08-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_intro_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view',
            field=models.IntegerField(blank=True, null=True, verbose_name='Просмотры'),
        ),
    ]
