# Generated by Django 4.1 on 2022-08-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='view',
            new_name='views',
        ),
    ]
